services:
  postgres:
    container_name: postgres
    image: "postgres:15"
    volumes:
      - ./postgresql/vault.dump:/vault.dump:ro
      - ./postgresql/restore_db.sh:/docker-entrypoint-initdb.d/restore.sh:ro
      - postgis-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=strongpassword
      - POSTGRES_DB=init
      - ALLOW_IP_RANGE=0.0.0.0/0

  redis:
    container_name: redis-tls
    build: .
    ports:
      - "6380:6380"

  handle_vault:
    build:
      context: ./dvault-backend
    container_name: handle_vault
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: ":8080"
      DB: "postgres://vault_rw:vault1234@postgres:5432/vault"
      DB_REDIS: "redis://@redis:6380/0"
      MOUNT_PATH: "/tmp/"
      STORAGE_TYPE: "postgres"
      CERT_DB_PATH_DVAULT: "/etc/handle_dvault/certs"
      CERT_REDIS_PATH_DVAULT: "/etc/handle_dvault/certs_redis"
    volumes:
      - "./certs_postgresql/:/etc/handle_dvault/certs"
      - "./certs_redis/:/etc/handle_dvault/certs_redis"
      - "/tmp/dvault:/tmp/"

volumes:
  postgis-db-volume:
